// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ZANGO_NORTHWIND_ODB_REPOSITORY_ODB_HXX
#define ZANGO_NORTHWIND_ODB_REPOSITORY_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "zango/northwind/types/repository.hpp"

#include "zango/northwind/odb/categories-odb.hxx"
#include "zango/northwind/odb/category_id-odb.hxx"
#include "zango/northwind/odb/customer_customer_demo-odb.hxx"
#include "zango/northwind/odb/customer_customer_demo_key-odb.hxx"
#include "zango/northwind/odb/customer_demographics-odb.hxx"
#include "zango/northwind/odb/customer_id-odb.hxx"
#include "zango/northwind/odb/customer_type_id-odb.hxx"
#include "zango/northwind/odb/customers-odb.hxx"
#include "zango/northwind/odb/employee_id-odb.hxx"
#include "zango/northwind/odb/employee_territories-odb.hxx"
#include "zango/northwind/odb/employee_territories_key-odb.hxx"
#include "zango/northwind/odb/employees-odb.hxx"
#include "zango/northwind/odb/order_details-odb.hxx"
#include "zango/northwind/odb/order_details_key-odb.hxx"
#include "zango/northwind/odb/order_id-odb.hxx"
#include "zango/northwind/odb/product_id-odb.hxx"
#include "zango/northwind/odb/products-odb.hxx"
#include "zango/northwind/odb/region-odb.hxx"
#include "zango/northwind/odb/region_id-odb.hxx"
#include "zango/northwind/odb/shipper_id-odb.hxx"
#include "zango/northwind/odb/shippers-odb.hxx"
#include "zango/northwind/odb/supplier-odb.hxx"
#include "zango/northwind/odb/supplier_id-odb.hxx"
#include "zango/northwind/odb/territory-odb.hxx"
#include "zango/northwind/odb/territory_id-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
}

#include "zango/northwind/odb/repository-odb.ixx"

#include <odb/post.hxx>

#endif // ZANGO_NORTHWIND_ODB_REPOSITORY_ODB_HXX
