// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "zango/northwind/odb/categories-odb-pgsql.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // categories
  //

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  persist_statement_name[] = "persist_zango_northwind_categories";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  find_statement_name[] = "find_zango_northwind_categories";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  update_statement_name[] = "update_zango_northwind_categories";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  erase_statement_name[] = "erase_zango_northwind_categories";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  query_statement_name[] = "query_zango_northwind_categories";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  erase_query_statement_name[] = "erase_query_zango_northwind_categories";

  const unsigned int access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::extra_statement_cache_type
  {
    pgsql::container_statements_impl< picutre_traits > picutre_;

    extra_statement_cache_type (
      pgsql::connection& c,
      image_type&,
      id_image_type&,
      pgsql::binding& id,
      pgsql::binding&,
      pgsql::native_binding& idn,
      const unsigned int* idt)
    : picutre_ (c, id, idn, idt)
    {
    }
  };

  // picutre_
  //

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  select_name[] = "select_zango_northwind_categories_picutre";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  insert_name[] = "insert_zango_northwind_categories_picutre";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  delete_name[] = "delete_zango_northwind_categories_picutre";

  const unsigned int access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  insert_types[] =
  {
    pgsql::int4_oid,
    pgsql::int8_oid,
    pgsql::text_oid
  };

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  select_statement[] =
  "SELECT "
  "\"northwind\".\"categories_picutre\".\"index\", "
  "\"northwind\".\"categories_picutre\".\"value\" "
  "FROM \"northwind\".\"categories_picutre\" "
  "WHERE \"northwind\".\"categories_picutre\".\"object_id_category_id\"=$1 ORDER BY \"northwind\".\"categories_picutre\".\"index\"";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  insert_statement[] =
  "INSERT INTO \"northwind\".\"categories_picutre\" "
  "(\"object_id_category_id\", "
  "\"index\", "
  "\"value\") "
  "VALUES "
  "($1, $2, $3)";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  delete_statement[] =
  "DELETE FROM \"northwind\".\"categories_picutre\" "
  "WHERE \"object_id_category_id\"=$1";

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  bind (pgsql::bind* b,
        const pgsql::bind* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace pgsql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = d.value_value.data ();
    b[n].capacity = d.value_value.capacity ();
    b[n].size = &d.value_size;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  grow (data_image_type& i,
        bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    if (t[1UL])
    {
      i.value_value.capacity (i.value_size);
      grew = true;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace pgsql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      pgsql::value_traits<
          index_type,
          pgsql::id_bigint >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.value_value.capacity ());
      pgsql::value_traits<
          value_type,
          pgsql::id_string >::set_image (
        i.value_value,
        size,
        is_null,
        v);
      i.value_null = is_null;
      i.value_size = size;
      grew = grew || (cap != i.value_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      pgsql::value_traits<
          index_type,
          pgsql::id_bigint >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      pgsql::value_traits<
          value_type,
          pgsql::id_string >::set_value (
        v,
        i.value_value,
        i.value_size,
        i.value_null);
    }
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, sts.id_binding ().count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  delete_ (void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      data_image_type& di (sts.data_image ());
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, id.count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::picutre_traits::
  erase (statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::id_type
  access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::zango::northwind::category_id, id_pgsql >::init (
        id,
        i.category_id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // category_id_
    //
    if (composite_value_traits< ::zango::northwind::category_id, id_pgsql >::grow (
          i.category_id_value, t + 0UL))
      grew = true;

    // category_name_
    //
    if (t[1UL])
    {
      i.category_name_value.capacity (i.category_name_size);
      grew = true;
    }

    // description_
    //
    if (t[2UL])
    {
      i.description_value.capacity (i.description_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // category_id_
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::zango::northwind::category_id, id_pgsql >::bind (
        b + n, i.category_id_value, sk);
      n += 1UL;
    }

    // category_name_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.category_name_value.data ();
    b[n].capacity = i.category_name_value.capacity ();
    b[n].size = &i.category_name_size;
    b[n].is_null = &i.category_name_null;
    n++;

    // description_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.description_value.data ();
    b[n].capacity = i.description_value.capacity ();
    b[n].size = &i.description_size;
    b[n].is_null = &i.description_null;
    n++;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    pgsql::statement_kind sk (pgsql::statement_select);
    composite_value_traits< ::zango::northwind::category_id, id_pgsql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // category_id_
    //
    if (sk == statement_insert)
    {
      ::zango::northwind::category_id const& v =
        o.category_id ();

      composite_value_traits< ::zango::northwind::category_id, id_pgsql >::init (
        i.category_id_value,
        v,
        sk);
    }

    // category_name_
    //
    {
      ::std::string const& v =
        o.category_name ();

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.category_name_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.category_name_value,
        size,
        is_null,
        v);
      i.category_name_null = is_null;
      i.category_name_size = size;
      grew = grew || (cap != i.category_name_value.capacity ());
    }

    // description_
    //
    {
      ::std::string const& v =
        o.description ();

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.description_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.description_value,
        size,
        is_null,
        v);
      i.description_null = is_null;
      i.description_size = size;
      grew = grew || (cap != i.description_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // category_id_
    //
    {
      ::zango::northwind::category_id& v =
        o.category_id ();

      composite_value_traits< ::zango::northwind::category_id, id_pgsql >::init (
        v,
        i.category_id_value,
        db);
    }

    // category_name_
    //
    {
      ::std::string& v =
        o.category_name ();

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.category_name_value,
        i.category_name_size,
        i.category_name_null);
    }

    // description_
    //
    {
      ::std::string& v =
        o.description ();

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.description_value,
        i.description_size,
        i.description_null);
    }
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    pgsql::statement_kind sk (pgsql::statement_select);
    {
      composite_value_traits< ::zango::northwind::category_id, id_pgsql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::persist_statement[] =
  "INSERT INTO \"northwind\".\"categories\" "
  "(\"category_id_category_id\", "
  "\"category_name\", "
  "\"description\") "
  "VALUES "
  "($1, $2, $3)";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::find_statement[] =
  "SELECT "
  "\"northwind\".\"categories\".\"category_id_category_id\", "
  "\"northwind\".\"categories\".\"category_name\", "
  "\"northwind\".\"categories\".\"description\" "
  "FROM \"northwind\".\"categories\" "
  "WHERE \"northwind\".\"categories\".\"category_id_category_id\"=$1";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::update_statement[] =
  "UPDATE \"northwind\".\"categories\" "
  "SET "
  "\"category_name\"=$1, "
  "\"description\"=$2 "
  "WHERE \"category_id_category_id\"=$3";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::erase_statement[] =
  "DELETE FROM \"northwind\".\"categories\" "
  "WHERE \"category_id_category_id\"=$1";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::query_statement[] =
  "SELECT "
  "\"northwind\".\"categories\".\"category_id_category_id\", "
  "\"northwind\".\"categories\".\"category_name\", "
  "\"northwind\".\"categories\".\"description\" "
  "FROM \"northwind\".\"categories\"";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"northwind\".\"categories\"";

  const char access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::table_name[] =
  "\"northwind\".\"categories\"";

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    id_image_type& i (sts.id_image ());
    init (i, obj.category_id ());

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // picutre_
    //
    {
      ::std::vector< char > const& v =
        obj.picutre ();

      picutre_traits::persist (
        v,
        esc.picutre_);
    }

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.category_id ());
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // picutre_
    //
    {
      ::std::vector< char > const& v =
        obj.picutre ();

      picutre_traits::update (
        v,
        esc.picutre_);
    }

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // picutre_
    //
    picutre_traits::erase (
      esc.picutre_);

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::pointer_type
  access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.category_id ());

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // picutre_
    //
    {
      ::std::vector< char >& v =
        obj.picutre ();

      picutre_traits::load (
        v,
        esc.picutre_);
    }
  }

  result< access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::object_type >
  access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::zango::northwind::categories, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"northwind\".\"categories_picutre\" CASCADE");
          db.execute ("DROP TABLE IF EXISTS \"northwind\".\"categories\" CASCADE");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"northwind\".\"categories\" (\n"
                      "  \"category_id_category_id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"category_name\" TEXT NOT NULL,\n"
                      "  \"description\" TEXT NULL)");
          db.execute ("CREATE TABLE \"northwind\".\"categories_picutre\" (\n"
                      "  \"object_id_category_id\" INTEGER NOT NULL,\n"
                      "  \"index\" BIGINT NOT NULL,\n"
                      "  \"value\" CHAR(1) NOT NULL,\n"
                      "  CONSTRAINT \"object_id_fk\"\n"
                      "    FOREIGN KEY (\"object_id_category_id\")\n"
                      "    REFERENCES \"northwind\".\"categories\" (\"category_id_category_id\")\n"
                      "    ON DELETE CASCADE)");
          db.execute ("CREATE INDEX \"categories_picutre_object_id_i\"\n"
                      "  ON \"northwind\".\"categories_picutre\" (\"object_id_category_id\")");
          db.execute ("CREATE INDEX \"categories_picutre_index_i\"\n"
                      "  ON \"northwind\".\"categories_picutre\" (\"index\")");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
